---
- hosts: localhost
  tasks:

    - name: Install required packages
      become: yes
      package:
        name:
          - libgcj
          - libgcj-devel
          - libstdc++
          - libstdc++-devel
          - gcj
        state: present

    - name: Install pdftk for Linux
      when: "'Linux' in ansible_system"
      become: yes
      package:
        name: pdftk
        state: present

    - name: Install pdftk for macOS
      when: "'Darwin' in ansible_system"
      become: yes
      shell: |
        brew install pdftk
      args:
        creates: /usr/local/bin/pdftk


    - name: ~/Downloads | Find csv
      find:
        paths: ~/Downloads
        recurse: false
        patterns: 
          - '*.csv'
          - '*.dmg'
      register: to_delete
    - name: ~/Downloads | Find compressed files
      find:
        paths: ~/Downloads
        recurse: false
        patterns: 
          - '*.zip'
          - '*.rar'
      register: download_compressed

    - name: ~/Downloads | Find PDF files
      find:
        paths: ~/Downloads
        recurse: false
        patterns: 
          - '*.pdf'
      register: pdf_files
        #    - name: Debug | ~/Downloads | Debug compressed files 
        #      ansible.builtin.debug:
        #        var: download_compressed
        #    - name: Apply filter while looping
        #      debug:
        #        msg: >-
        #          {{ item.path | regex_replace('^([^\.]*).*', '\1') }}
        #      loop: "{{ download_compressed.files }}"

    - name: Create variable with file paths without extension
      set_fact:
        file_paths_without_extension: "{{ download_compressed.files | map(attribute='path') | map('regex_replace', '\\..*', '') | list }}"

    - name: ~/Downloads | Delete know files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ to_delete.files }}"

    - name: ~/Downloads | Delete uncompressed folders
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ file_paths_without_extension }}"
